### ISSUE TITLE
多实例支持问题

### ISSUE THREAD

**Issue by rhwong** [wutongshufqw/amiyabot-tools#3]
我在Amiya中启用了3个GO-CQHTTP实例，并同时开启用于负载均衡。
但是我发现小工具插件只会在其中一个实例中完整启用，具体表现为：
1.运行AmiyaBot时，账号A会发送给管理员：“兔兔启动成功或小工具插件安装成功！”
2.账号A私聊可以使用[兔兔小工具全局管理]
3.账号A群聊可以正常使用全局启用的功能，使用[兔兔小工具管理]指令可以看到这些启用。
4.运行AmiyaBot时，账号B**不会**发送给管理员：“兔兔启动成功或小工具插件安装成功！”
5.账号B私聊**不可以**使用[兔兔小工具全局管理]，表现为无反应
6.账号B群聊**无法使用**任何小工具插件功能，使用[兔兔小工具管理]指令会回复如下内容：
```
功能列表：
请输入序号开启或关闭功能
回复“退出”退出
```
我不太清楚这是否符合程序预期，如果不正常是不是我哪里没有设置对？

**Comment by wutongshufqw** [comment]
请查看多实例是否配置正确
![image](https://github.com/wutongshufqw/amiyabot-tools/assets/87960738/86a0d960-fb74-4abc-ba2f-47d583ffcf2a)

**Comment by rhwong** [comment]
哦这里的配置是干这个的啊，我还以为只是那个什么重启功能的
我根本就没配置这里）））

**Comment by rhwong** [comment]
更改并重启后貌似还是不行，或者操作员不可为同一个Q吗？

**Comment by wutongshufqw** [comment]
这个功能需要你是管理员，是在兔兔控制台左侧的管理员页签中设置

**Comment by rhwong** [comment]
![image](https://github.com/wutongshufqw/amiyabot-tools/assets/58497504/bb2313a1-ca77-474a-9079-b8385423c6af)
但是我已经是管理员了呃..

**Comment by rhwong** [comment]
~~我之前也已经设置了管理员帐号，并且使用管理员帐号分别对ABC三个实例账号发送了管理指令，其中只有之前一直都正常的A可以用。~~
刚才因为更新了插件，插件可能重启了一下，然后AB都发送了“兔兔启动成功或小工具插件安装成功！”这个开启提示，只有C不行，原理不明
我什么都没做

**Comment by rhwong** [comment]
通过检查，发现该帐号所有私聊消息均无法发送，原理未知。
![image](https://github.com/wutongshufqw/amiyabot-tools/assets/58497504/965a6492-234e-4834-9a16-eaa02820ec2e)
图中所示有消息发送，但是实际没发送出去。
已知另外两个帐号是WATCH协议，故障帐号使用的是Android_Pad协议。我去go-cqhttp提一个issue。

**Comment by rhwong** [comment]
https://github.com/Mrs4s/go-cqhttp/issues/2140

**Comment by rhwong** [comment]
Mrs4s/go-cqhttp#2140
